# Generated by Django 5.0.14 on 2026-01-14 00:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('classification', models.CharField(choices=[('none', 'Nessuno'), ('person', 'Persona'), ('animal_lg', 'Animale Grande'), ('animal_sm', 'Animale Piccolo'), ('unknown', 'Sconosciuto'), ('tamper', 'Manomissione')], default='unknown', max_length=15)),
                ('priority', models.CharField(choices=[('critical', 'Critico'), ('high', 'Alto'), ('medium', 'Medio'), ('low', 'Basso')], default='medium', max_length=10)),
                ('pir_main', models.BooleanField(default=False, help_text='PIR principale attivato')),
                ('pir_backup', models.BooleanField(default=False, help_text='PIR backup attivato')),
                ('motion_confirmed', models.BooleanField(default=False, help_text='Movimento confermato da entrambi i PIR')),
                ('tamper_detected', models.BooleanField(default=False, help_text='Manomissione rilevata')),
                ('accel_x', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('accel_y', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('accel_z', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('confidence', models.PositiveSmallIntegerField(default=0, help_text='Confidenza classificazione (0-100)')),
                ('duration_ms', models.PositiveIntegerField(default=0, help_text='Durata movimento in millisecondi')),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Dati grezzi per analisi')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_events', to='nodes.node')),
            ],
            options={
                'verbose_name': 'Evento Sicurezza',
                'verbose_name_plural': 'Eventi Sicurezza',
                'db_table': 'security_events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Attivo'), ('acknowledged', 'Preso in Carico'), ('resolved', 'Risolto'), ('false_pos', 'Falso Positivo'), ('ignored', 'Ignorato')], default='active', max_length=15)),
                ('priority', models.CharField(choices=[('critical', 'Critico'), ('high', 'Alto'), ('medium', 'Medio'), ('low', 'Basso')], max_length=10)),
                ('classification', models.CharField(choices=[('none', 'Nessuno'), ('person', 'Persona'), ('animal_lg', 'Animale Grande'), ('animal_sm', 'Animale Piccolo'), ('unknown', 'Sconosciuto'), ('tamper', 'Manomissione')], max_length=15)),
                ('siren_activated', models.BooleanField(default=False, help_text='Sirena attivata localmente')),
                ('lights_activated', models.BooleanField(default=False, help_text='Luci allarme attivate')),
                ('actuation_duration', models.PositiveIntegerField(default=30, help_text='Durata attuazione in secondi')),
                ('acknowledged_by', models.CharField(blank=True, help_text='Utente che ha preso in carico', max_length=100)),
                ('resolution_notes', models.TextField(blank=True, help_text='Note sulla risoluzione')),
                ('notifications_sent', models.JSONField(blank=True, default=list, help_text='Lista canali notifica usati')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='nodes.node')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alarm', to='security.securityevent')),
            ],
            options={
                'verbose_name': 'Allarme',
                'verbose_name_plural': 'Allarmi',
                'db_table': 'alarms',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_armed', models.BooleanField(default=True)),
                ('alarm_delay_seconds', models.PositiveSmallIntegerField(default=0, help_text='Ritardo prima di attivare allarme')),
                ('entry_delay_seconds', models.PositiveSmallIntegerField(default=30, help_text='Tempo per disarmare dopo ingresso')),
                ('notify_on_alarm', models.BooleanField(default=True)),
                ('notify_channels', models.JSONField(blank=True, default=list, help_text='Canali notifica per questa zona')),
                ('nodes', models.ManyToManyField(limit_choices_to={'node_type': 'SEC'}, related_name='security_zones', to='nodes.node')),
            ],
            options={
                'verbose_name': 'Zona Sicurezza',
                'verbose_name_plural': 'Zone Sicurezza',
                'db_table': 'security_zones',
            },
        ),
        migrations.CreateModel(
            name='SystemArmState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('mode', models.CharField(choices=[('armed', 'Armato'), ('disarmed', 'Disarmato'), ('armed_stay', 'Armato Casa'), ('armed_away', 'Armato Via')], max_length=15)),
                ('previous_mode', models.CharField(blank=True, choices=[('armed', 'Armato'), ('disarmed', 'Disarmato'), ('armed_stay', 'Armato Casa'), ('armed_away', 'Armato Via')], max_length=15)),
                ('changed_by', models.CharField(help_text='Utente o sistema che ha cambiato stato', max_length=100)),
                ('change_source', models.CharField(default='app', help_text='Origine del cambio (app, api, schedule, system)', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('nodes_affected', models.ManyToManyField(blank=True, related_name='arm_states', to='nodes.node')),
            ],
            options={
                'verbose_name': 'Stato Armamento',
                'verbose_name_plural': 'Stati Armamento',
                'db_table': 'system_arm_states',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['node', '-timestamp'], name='security_ev_node_id_95fb5a_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['classification', '-timestamp'], name='security_ev_classif_0069b0_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['priority', '-timestamp'], name='security_ev_priorit_53319e_idx'),
        ),
        migrations.AddIndex(
            model_name='alarm',
            index=models.Index(fields=['status', '-triggered_at'], name='alarms_status_e81aec_idx'),
        ),
        migrations.AddIndex(
            model_name='alarm',
            index=models.Index(fields=['node', '-triggered_at'], name='alarms_node_id_d13979_idx'),
        ),
        migrations.AddIndex(
            model_name='alarm',
            index=models.Index(fields=['priority', 'status'], name='alarms_priorit_fc6169_idx'),
        ),
    ]
