# Generated by Django 5.0.14 on 2026-01-14 00:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(db_index=True, help_text='ID univoco del nodo (es. GW-001, AMB-001)', max_length=20, unique=True)),
                ('mac_address', models.CharField(blank=True, help_text='MAC address del nodo', max_length=17)),
                ('name', models.CharField(help_text='Nome descrittivo del nodo', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Descrizione e note sul nodo')),
                ('node_type', models.CharField(choices=[('GW', 'Gateway'), ('AMB', 'Ambientale'), ('SEC', 'Sicurezza')], default='AMB', max_length=3)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('warning', 'Warning'), ('error', 'Errore'), ('maintenance', 'Manutenzione')], default='offline', max_length=15)),
                ('is_armed', models.BooleanField(default=True, help_text='Sistema di sicurezza armato (solo per nodi SEC)')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_description', models.CharField(blank=True, help_text="Descrizione posizione (es. 'Angolo nord-est')", max_length=200)),
                ('firmware_version', models.CharField(blank=True, default='1.0.0', max_length=20)),
                ('last_seen', models.DateTimeField(blank=True, help_text='Ultimo heartbeat ricevuto', null=True)),
                ('uptime_seconds', models.PositiveIntegerField(default=0, help_text="Secondi dall'ultimo riavvio")),
                ('boot_count', models.PositiveIntegerField(default=0, help_text='Numero di riavvii')),
                ('battery_voltage', models.DecimalField(blank=True, decimal_places=2, help_text='Tensione batteria in V', max_digits=4, null=True)),
                ('battery_percentage', models.PositiveSmallIntegerField(blank=True, help_text='Percentuale carica batteria', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_charging', models.BooleanField(default=False, help_text='Batteria in carica (pannello solare)')),
                ('solar_voltage', models.DecimalField(blank=True, decimal_places=2, help_text='Tensione pannello solare in V', max_digits=4, null=True)),
                ('rssi', models.SmallIntegerField(blank=True, help_text='Potenza segnale WiFi/mesh (dBm)', null=True)),
                ('mesh_neighbors', models.PositiveSmallIntegerField(default=0, help_text='Numero di nodi vicini nella mesh')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Configurazione JSON del nodo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('gateway', models.ForeignKey(blank=True, help_text='Gateway di riferimento', limit_choices_to={'node_type': 'GW'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_nodes', to='nodes.node')),
            ],
            options={
                'verbose_name': 'Nodo',
                'verbose_name_plural': 'Nodi',
                'db_table': 'nodes',
                'ordering': ['node_type', 'node_id'],
            },
        ),
        migrations.CreateModel(
            name='NodeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_type', models.CharField(choices=[('boot', 'Avvio'), ('shutdown', 'Spegnimento'), ('error', 'Errore'), ('warning', 'Warning'), ('ota_start', 'OTA Avviato'), ('ota_success', 'OTA Completato'), ('ota_fail', 'OTA Fallito'), ('config', 'Cambio Configurazione'), ('batt_low', 'Batteria Bassa'), ('batt_crit', 'Batteria Critica'), ('offline', 'Offline'), ('online', 'Online')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='nodes.node')),
            ],
            options={
                'verbose_name': 'Evento Nodo',
                'verbose_name_plural': 'Eventi Nodi',
                'db_table': 'node_events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NodeHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('uptime_seconds', models.PositiveIntegerField(default=0)),
                ('free_heap_kb', models.PositiveIntegerField(default=0)),
                ('rssi', models.SmallIntegerField(null=True)),
                ('battery_percentage', models.PositiveSmallIntegerField(null=True)),
                ('mesh_neighbors', models.PositiveSmallIntegerField(default=0)),
                ('status_code', models.PositiveSmallIntegerField(default=0)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='nodes.node')),
            ],
            options={
                'verbose_name': 'Heartbeat',
                'verbose_name_plural': 'Heartbeats',
                'db_table': 'node_heartbeats',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['node_type', 'status'], name='nodes_node_ty_ccdd41_idx'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['last_seen'], name='nodes_last_se_2ac632_idx'),
        ),
        migrations.AddIndex(
            model_name='nodeevent',
            index=models.Index(fields=['node', '-timestamp'], name='node_events_node_id_e17d4e_idx'),
        ),
        migrations.AddIndex(
            model_name='nodeevent',
            index=models.Index(fields=['event_type', '-timestamp'], name='node_events_event_t_3f12d3_idx'),
        ),
        migrations.AddIndex(
            model_name='nodeheartbeat',
            index=models.Index(fields=['node', '-timestamp'], name='node_heartb_node_id_25a320_idx'),
        ),
    ]
