# Generated by Django 5.0.14 on 2026-01-14 00:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregate_type', models.CharField(choices=[('hourly', 'Orario'), ('daily', 'Giornaliero'), ('weekly', 'Settimanale'), ('monthly', 'Mensile')], max_length=10)),
                ('period_start', models.DateTimeField(db_index=True)),
                ('period_end', models.DateTimeField()),
                ('reading_count', models.PositiveIntegerField(default=0)),
                ('temperature_min', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('temperature_max', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('temperature_avg', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('humidity_min', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('humidity_max', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('humidity_avg', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('pressure_min', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('pressure_max', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('pressure_avg', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('light_min', models.PositiveIntegerField(null=True)),
                ('light_max', models.PositiveIntegerField(null=True)),
                ('light_avg', models.PositiveIntegerField(null=True)),
                ('soil_min', models.PositiveSmallIntegerField(null=True)),
                ('soil_max', models.PositiveSmallIntegerField(null=True)),
                ('soil_avg', models.PositiveSmallIntegerField(null=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_aggregates', to='nodes.node')),
            ],
            options={
                'verbose_name': 'Aggregato Sensori',
                'verbose_name_plural': 'Aggregati Sensori',
                'db_table': 'sensor_aggregates',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['node', 'aggregate_type', '-period_start'], name='sensor_aggr_node_id_d43c7e_idx')],
                'unique_together': {('node', 'aggregate_type', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='SensorAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('alert_type', models.CharField(choices=[('temp_low', 'Temperatura Bassa'), ('temp_high', 'Temperatura Alta'), ('hum_low', 'Umidità Bassa'), ('hum_high', 'Umidità Alta'), ('soil_dry', 'Suolo Secco'), ('soil_wet', 'Suolo Bagnato'), ('sensor_off', 'Sensore Offline'), ('sensor_err', 'Errore Sensore')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critico')], default='warning', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, help_text="Valore che ha triggerato l'alert", max_digits=10, null=True)),
                ('threshold', models.DecimalField(decimal_places=2, help_text='Soglia superata', max_digits=10, null=True)),
                ('message', models.TextField(blank=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.CharField(blank=True, max_length=100)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('notification_channels', models.JSONField(blank=True, default=list, help_text='Canali su cui è stata inviata la notifica')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_alerts', to='nodes.node')),
            ],
            options={
                'verbose_name': 'Alert Sensore',
                'verbose_name_plural': 'Alert Sensori',
                'db_table': 'sensor_alerts',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['node', '-timestamp'], name='sensor_aler_node_id_8b8b0f_idx'), models.Index(fields=['alert_type', 'is_resolved'], name='sensor_aler_alert_t_f6af2f_idx'), models.Index(fields=['-timestamp', 'severity'], name='sensor_aler_timesta_5cc145_idx')],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, help_text='Temperatura in °C', max_digits=5, null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, help_text='Umidità relativa in %', max_digits=5, null=True)),
                ('pressure', models.DecimalField(blank=True, decimal_places=2, help_text='Pressione atmosferica in hPa', max_digits=6, null=True)),
                ('light_lux', models.PositiveIntegerField(blank=True, help_text='Luminosità in lux', null=True)),
                ('soil_moisture_raw', models.PositiveSmallIntegerField(blank=True, help_text='Valore ADC grezzo (0-4095)', null=True)),
                ('soil_moisture_percent', models.PositiveSmallIntegerField(blank=True, help_text='Umidità suolo in %', null=True)),
                ('battery_voltage', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='nodes.node')),
            ],
            options={
                'verbose_name': 'Lettura Sensore',
                'verbose_name_plural': 'Letture Sensori',
                'db_table': 'sensor_readings',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['node', '-timestamp'], name='sensor_read_node_id_91eff8_idx'), models.Index(fields=['-timestamp'], name='sensor_read_timesta_e41de6_idx')],
            },
        ),
    ]
